export enum RobotState {
    WAITING = "EN ATTENTE",
    MISSION_ON_GOING = "EN MISSION",
    RETURNING_TO_BASE = "EN RETOUR A LA BASE",
    LOW_BATTERY = "BATTERIE FAIBLE",
    UPDATE = "MISE A JOUR",
    OFFLINE = "HORS LIGNE"
}