export enum Topic {
    start_mission = '/start_mission_command',
    stop_mission = '/stop_mission_command',
    return_base = '/return_to_base',
    identify_command1 = '/robot_1/identify_command',
    identify_command2 = '/robot_2/identify_command',
    peer_to_peer1 = '/robot_1/peer_to_peer_command',
    peer_to_peer2 = '/robot_2/peer_to_peer_command',
    mission_status1 = '/robot_1/mission_status',
    mission_status2 = '/robot_2/mission_status',
    map = '/map',
    physical_robot_map = '/merge_map',
    gazebo_mission_status = '/gazebo/mission_status',
    log_robot1 = '/robot_1/log',
    log_robot2 = '/robot_2/log',
    log_gazebo = '/gazebo/log',
    update_code_robot1 = '/robot_1/update_code',
    update_code_robot2 = '/robot_2/update_code',
    update_code_gazebo = '/gazebo/update_code',
    geofence = '/geofence/bounds',
    robot1_pose_with_distance = '/robot_1/pose_with_distance',
    robot2_pose_with_distance = '/robot_2/pose_with_distance',
    gazebo1_pose_with_distance = '/limo1/pose_with_distance',
    gazebo2_pose_with_distance = '/limo2/pose_with_distance',
}