# Dockerfile

# Use Node.js to build the app
FROM node:20 AS build

WORKDIR /client

# Clone the repository
RUN git clone https://github.com/thomas-rou/Geppetto.git\
    && cd geppetto\
    && git checkout develop\
    && git pull

WORKDIR /client/geppetto/application/client

# Install Angular CLI
RUN npm install -g @angular/cli

# Install dependencies
RUN npm ci

# Expose the port
EXPOSE 4200

# Start the app
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
