# Dockerfile

# Use Node.js to build the app
FROM node:20 AS build

WORKDIR /server

# Clone the repository
RUN git clone https://github.com/thomas-rou/Geppetto.git\
    && cd geppetto\
    && git checkout feature/create_db_container\
    && git pull

WORKDIR /server/geppetto/application/server

# Install dependencies
RUN npm ci

# Expose the port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
